# Generated by Django 3.2.7 on 2022-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_message_gonderen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='baxilma',
            field=models.BooleanField(default=False),
        ),
    ]
