# Generated by Django 3.2.7 on 2022-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_message_baxilma'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tesdiq',
            field=models.BooleanField(default=None),
        ),
    ]
