# Generated by Django 3.2.7 on 2022-02-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_message_tesdiq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tesdiq',
            field=models.BooleanField(default=False),
        ),
    ]
