# Generated by Django 3.2.7 on 2022-03-26 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_message_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Notice',
        ),
    ]
