# Generated by Django 3.2.7 on 2022-03-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='tesdiq',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
