# Generated by Django 3.2.7 on 2022-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_notice_tesdiq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='tesdiq',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
