# Generated by Django 3.2.7 on 2022-03-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_notice_tesdiq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='baxilma',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
