# Generated by Django 3.2.7 on 2022-06-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='animal_category',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='animal_gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
