# Generated by Django 3.2.7 on 2022-07-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20220616_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Şəkil əlavə etmək:'),
        ),
    ]
