# Generated by Django 3.2.7 on 2021-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='money',
            field=models.IntegerField(),
        ),
    ]
